### PR TITLE
Feature/ops mpi cuda

### PR DESCRIPTION
**Pull request by TobyFlynn**
OPS integration changes

### CODE REVIEW

**Comment by gihanmudalige** [comment]
@TobyFlynn , have you run the usual tests with this branch and the feature/tridiagonal _distributed branch of the tridiagonal solver (which you have currently pull-requested there as well). I am not seeing the test.sh pass for the adi application with the above combination. Am I doing something wrong ?

I get : 
============> Running DEV_SEQ
mv: cannot stat 'adi.h5': No such file or directory

which means that the hdf5 file is not generated from the dev-seq test.

**Comment by gihanmudalige** [comment]
@TobyFlynn  Are these latest commits fixes for the OPS ADI solver tests to pass?

**Comment by TobyFlynn** [comment]
@gihanmudalige These commits just get the MPI solvers to pass some new tests I wrote to make sure they don't alter any of the padded memory. The next thing that I'll have a look at is the sequential CUDA solver not handling padding in the y dimension.

**Comment by TobyFlynn** [comment]
Jianping has checked that the OPS applications he wrote are producing good results so I think this is ready to be merged onto master now

**Review by reguly — APPROVED** [review]

**Pull request merged**
