### PR TITLE
Feature/cmake update

### PR DESCRIPTION
**Pull request by bgd54**
CMake updates using findCUDAToolkit and export to install the library with `cmake --install`.

Removed the INTEL_CC option since it was broken. Instead, it is on when the compiler is, in fact, the Intel compiler and assumes gcc otherwise.

FindCUDA is deprecated, so I use FindCUDAToolkit and first-hand language support for CUDA. MPI, OpenMP and cublas added as traditional libraries.

Exporting 4 targets: libtrid::tridcpu, libtrid::tridcpu_mpi, libtrid::tridcuda and libtrid::tridcuda_mpi. Exporting with profiling is broken at the moment.

Please let me know if I should change something :)

### CODE REVIEW

**Comment by gihanmudalige** [comment]
@bgd54 Could you rebase this on the current master, this will help a lot in testing this out. Thanks.

**Comment by bgd54** [comment]
I rebased the branch. I will check tomorrow to see if it works.

**Comment by bgd54** [comment]
Hi!

We had some linking issues with CUDA aware MPI. It generated a segfault for us when CMake used static linking to CUDA runtime. Hence, all CUDA versions use dynamic linking (https://github.com/OP-DSL/tridsolver/blob/206ecf15c839569e824d64dcfec06a27453860e1/scalar/CMakeLists.txt#L102), only the CUDA aware MPI required the dynamic linking though.
Cheers

**Comment by bgd54** [comment]
#12 contains this work as well.

**Pull request closed without merging**
