### PR TITLE
All the MPI and latency hiding developments

### PR DESCRIPTION
**Pull request by reguly**
PR for all the recent developments

### CODE REVIEW

**Comment by gihanmudalige** [comment]
The build on Kos breaks for some versions of the ADI application.  Was the application builds tested ?

**Comment by gihanmudalige** [comment]
Existing OPS apps also does not build with this latest : 
 
/opt/intel/parallelstudio/2017/update2/x86_64/impi/2017.2.174/intel64//bin/mpicxx -std=c++11 -fp-model strict -fp-model source -prec-div -prec-sqrt  -qopenmp -I/rr-home/gihan/OPS/ops/c/include -L/rr-home/gihan/OPS/ops/c/lib/intel adi_ops.cpp -I. ./MPI_OpenMP/adi_cpu_kernels.cpp -lops_seq -lops_hdf5_seq -lops_trid_seq -L/rr-home/gihan/tridsolver/scalar/build//lib -ltridcpu -L/opt/compilers/intel/intelPS-2015/lib/intel64/ -limf -lintlc -lsvml -lirng -liomp5 -lcilkrts \
 -L/opt/hdf5/1.8.18/intel/15.0u6/impi/5.0u3//lib -lhdf5_hl -lhdf5 -lz -o adi_openmp
./MPI_OpenMP/preproc_kernel_cpu_kernel.cpp(169): warning #15552: loop was not vectorized with "simd"
nvcc   -O3 -arch sm_35 -std=c++11 --ptxas-options=-v -Xptxas -dlcm=cg  -I/rr-home/gihan/OPS/ops/c/include -I. -c -o ./CUDA/adi_kernels_cu.o ./CUDA/adi_kernels.cu
ptxas info    : 0 bytes gmem, 136 bytes cmem[3]
ptxas info    : Compiling entry function '_Z18ops_preproc_kernelPdS_S_S_S_S_S_S_S_S_S_iiiiii' for 'sm_35'
ptxas info    : Function properties for _Z18ops_preproc_kernelPdS_S_S_S_S_S_S_S_S_S_iiiiii
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 36 registers, 432 bytes cmem[0]
ptxas info    : Compiling entry function '_Z15ops_init_kernelPdiiiiii' for 'sm_35'
ptxas info    : Function properties for _Z15ops_init_kernelPdiiiiii
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 8 registers, 352 bytes cmem[0], 4 bytes cmem[2]
/opt/intel/parallelstudio/2017/update2/x86_64/impi/2017.2.174/intel64//bin/mpicxx -std=c++11 -fp-model strict -fp-model source -prec-div -prec-sqrt  -I/opt/cuda/9.1.85/toolkit//include -I/rr-home/gihan/tridsolver/scalar/build//include -I/rr-home/gihan/OPS/ops/c/include -L/rr-home/gihan/OPS/ops/c/lib/intel -L/opt/cuda/9.1.85/toolkit//lib64 adi_ops.cpp ./CUDA/adi_kernels_cu.o -lcudart -lops_cuda -lops_trid_cuda -lops_hdf5_seq -L/rr-home/gihan/tridsolver/scalar/build//lib -ltridcuda -L/opt/hdf5/1.8.18/intel/15.0u6/impi/5.0u3//lib -lhdf5_hl -lhdf5 -lz -o adi_cuda
/rr-home/gihan/tridsolver/scalar/build//lib/libtridcuda.so: undefined reference to `cublasSgeam'
/rr-home/gihan/tridsolver/scalar/build//lib/libtridcuda.so: undefined reference to `cublasDgeam'
/rr-home/gihan/tridsolver/scalar/build//lib/libtridcuda.so: undefined reference to `cublasCreate_v2'
Makefile:190: recipe for target 'adi_cuda' failed
make: *** [adi_cuda] Error 1

**Comment by TobyFlynn** [comment]
@gihanmudalige I was having the same issue with the ADI test app in this repo. The fix was to change the following line in the ADI CMakelists.txt file from:

set(CUDA_LIBRARIES ${CUDA_TOOLKIT_ROOT_DIR}/lib64/libcudart.so)

to:

set(CUDA_LIBRARIES ${CUDA_TOOLKIT_ROOT_DIR}/lib64/libcudart.so ${CUDA_TOOLKIT_ROOT_DIR}/lib64/libcublas.so)

I don't know whether the same fix will sort out the OPS apps as well.

**Comment by bgd54** [comment]
@gihanmudalige @TobyFlynn I'm sorry I was the one who removed the hardcoded path to cublas (I had somewhere else, so I've got errors with this one). I think the proper way with findCuda and pre-CMake 3.9 is to use cuda_add_cublas_to_target like in scalar/test/CMakeLists.txt:71 (https://github.com/OP-DSL/tridsolver/blob/89c97db5ddd1279749070548333997bff73b2e0b/scalar/test/CMakeLists.txt#L71). I forgot to add it to the library itself.
I haven't found any other automatic way to locate cublas. At least not before CMake 3.17.3 which may be a bit too new to add it as a requirement.

**Comment by gihanmudalige** [comment]
Thanks Toby.  Yes I believe this will fix the issue.  I will try it out later tonight.  Merge the fix to master when you are ready.

**Comment by TobyFlynn** [comment]
@bgd54 Thank you, just changed it over to find cublas automatically.

**Comment by TobyFlynn** [comment]
I've gotten the catch test cases to build and pass for all CPU and CUDA versions.

For the MPI+CPU ADI test app, I've gotten the GATHER_SCATTER and ALLGATHER versions working correctly. When I try the two latency hiding versions I get "double free or corruption (!prev)" errors. I'll have a look tomorrow to try and work out whether its something I'm doing in the ADI app or not.

For the MPI+CUDA ADI test app, the ALLGATHER version is correctly working. The two latency hiding version work correctly when the ADI app runs for a small number of iterations (e.g. 10) but when large numbers of iterations (e.g. 50) are run I get "Runtime API error : invalid resource handle." errors. These get caught in the preprocessing section of the code but only occur when the latency hiding versions are used. I'll see whether there is something I'm not doing correctly when using the latency hiding versions tomorrow and let you guys know.

**Comment by TobyFlynn** [comment]
Hi everyone, I think the issue was with the MPI configuration on my machine. I tested it on a different setup and it worked correctly so everything is good on my end now

**Comment by reguly** [comment]
Pushed in some improvements for testing performance (multithreaded initialization), and made the default build config Release instead of Debug (not sure if so far we have been testing Debug or Release... I certainly have been looking at Debug)

**Pull request merged**
